TestForNVCoding/Models/TestForNVCodingContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TestForNVCoding.Models
{
    public class TestForNVCodingContext : DbContext
    {
  
        public TestForNVCodingContext() : base("name=TestForNVCodingContext")
        {
        }

        public System.Data.Entity.DbSet<TestForNVCoding.Models.UserProfiles> UserProfiles { get; set; }
    }
}

TestForNVCoding/Models/UserProfiles.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestForNVCoding.Helpers;

namespace TestForNVCoding.Models
{
    public class UserProfiles
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
        [Required]
        [StringLength(int.MaxValue, MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DataType(DataType.Upload)]
        public string Avatar { get; set; }
        [SkypeValidate]
        public string Skype { get; set; }
        [DataType(DataType.Upload)]
        public string Signature { get; set; }
        
    }
}

TestForNVCoding/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestForNVCoding.Helpers;
using TestForNVCoding.Models;

namespace TestForNVCoding.Controllers
{
    public class UserProfilesController : Controller
    {
        private TestForNVCodingContext db = new TestForNVCodingContext(); 
        // GET: UserProfile
        public async Task<ActionResult> Index()
        {
            return View(await db.UserProfiles.ToListAsync());
        }
        /// <summary>
        /// Action для создания и редактирования UserProfiles
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> AddOrFix(int? id)
        {
            //Если id отсутствует то, создать, в противном случае изменить
            if (id == null)
            {
                //Если прийдётся заменять эту ветку, лучше использовать Ajax
                UserProfiles newUserProfile = new UserProfiles();
                newUserProfile.Name = "NameExample";
                newUserProfile.Email = "Email@example.com";
                db.UserProfiles.Add(newUserProfile);
                await db.SaveChangesAsync();
                return View(newUserProfile);
            }
            UserProfiles userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
                return PartialView("_AddOrFix");
            return View(userProfile);
        } 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddOrFix([Bind(Include = "Id,Name,Email,Avatar,Skype,Signature")] UserProfiles userProfile, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                int userId;
                if (userProfile.Id != null)
                {
                    userId = userProfile.Id;
                }
                else
                {
                    userId = 0;// в папку с 0 будет сохранять все изображения с ошибкой
                }
                UploadAvatar(file, userId);
                db.UserProfiles.Add(userProfile);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }
        /// <summary>
        /// Ответ сервера на Ajax запрос, сохраняет юзера если он валидный
        /// </summary>
        /// <param name="userData"></param>
        [HttpPost]
        public void Fix(UserData userData)
        {
            try //На случай если пользователь сам попробует изменить запрос
            {
                //Работает только с Ajax
                if (Request.IsAjaxRequest())
                {
                    UserProfiles userProfile = db.UserProfiles.Find(userData.id);
                    userProfile.Name = userData.Name;
                    userProfile.Email = userData.Email;
                    userProfile.Avatar = UploadAvatar(userData.Avatar, userProfile.Id);
                    userProfile.Signature = userData.Signature;
                    userProfile.Skype = userData.Skype;
                    db.Entry(userProfile).State = EntityState.Modified;
                    db.SaveChangesAsync();
                }
            }
            catch { }
        }
        /// <summary>
        /// Сохраняет изображения(можно добавить валидацию, если будет необходимость), путь ~/Content/Images/UserAvatars/{id}/{fileName}
        /// </summary>
        /// <param name="file">загружаемый файл на сервер</param>
        /// <param name="userId">id UserProfiles</param>
        /// <returns></returns>
        [HttpGet]
        public string UploadAvatar(HttpPostedFileBase file, int userId)
        {

            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Server.MapPath("~/Content/Images/UserAvatars/" + userId.ToString() + "/");
                var filePathToSave = path + fileName;
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                file.SaveAs(filePathToSave);
                var stringToReturn = userId.ToString() + "/" + fileName;
                return stringToReturn;
            }
            return "";
        }
    }
}

TestForNVCoding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "UserProfiles", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "UserProfiles")</li>
                    <li>@Html.ActionLink("New", "AddOrFix", "UserProfiles")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Created by Mats'ko Alexei</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestForNVCoding/Views/UserProfiles/AddOrFix.cshtml
@{
    ViewBag.Title = "Edit";
}

<div id="container">
    @Html.Partial("_AddOrFixAjax")
</div>

@section Scripts
{
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
    <script src="http://ajax.microsoft.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
    <script src="@Url.Content("~/Scripts/AjaxRequests.js")"></script>
}

TestForNVCoding/Views/UserProfiles/Index.cshtml
@model IEnumerable<TestForNVCoding.Models.UserProfiles>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "AddOrFix")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skype)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Signature)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @if(((item.Avatar) != null )&&((item.Avatar) != "") )
                {
                try { 
                    
                <img src='@Url.Content("~/Content/Images/UserAvatars/" + @item.Avatar)' alt="image" style="width:100px;height:100px;">
                    }
                catch { }
                    
                }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Skype)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Signature)
        </td>
        <td>
            @Html.ActionLink("Edit", "AddOrFix", new { id = item.Id })
        </td>
    </tr>
}

</table>

TestForNVCoding/Views/UserProfiles/_AddOrFixAjax.cshtml
@model TestForNVCoding.Models.UserProfiles
<h2>Edit</h2>
@using (Ajax.BeginForm(new AjaxOptions {  }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id, new { id = "userId" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="editor-field">
                <div>
                    <input type="file" name="file" value="" id="Avatar" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Avatar)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Skype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Skype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Skype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Signature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Signature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Signature, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
            }
<div>
    @Html.ActionLink("Back to List", "Index")
</div>